// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.intDesign.homeHub.infrastructure.graphql.types;

/**
 * Room Type
 */
public enum RoomType {
    KITCHEN("KITCHEN"),

    BATH_ROOM("BATH_ROOM"),

    HALLWAY("HALLWAY"),

    BED_ROOM("BED_ROOM"),

    LIVING_ROOM("LIVING_ROOM"),

    INVALID("INVALID"),

    /**
     * Auto generated constant for unknown enum values
     */
    $UNKNOWN("$UNKNOWN");

    private final String rawValue;

    RoomType(String rawValue) {
        this.rawValue = rawValue;
    }

    public String rawValue() {
        return rawValue;
    }

    public static RoomType safeValueOf(String rawValue) {
        for (RoomType enumValue : values()) {
            if (enumValue.rawValue.equals(rawValue)) {
                return enumValue;
            }
        }
        return RoomType.$UNKNOWN;
    }
}
