// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.intDesign.homeHub.infrastructure.graphql.types;

import com.apollographql.apollo.api.Input;
import com.apollographql.apollo.api.InputFieldMarshaller;
import com.apollographql.apollo.api.InputType;
import com.apollographql.apollo.api.internal.Utils;

import org.jetbrains.annotations.NotNull;
import org.jetbrains.annotations.Nullable;

public final class RoomCreateViewModel implements InputType {
    private final double lenght;

    private final double height;

    private final double width;

    private final Input<Double> customLenght;

    private final Input<Double> customWidth;

    private final Input<Double> customHeightOne;

    private final Input<Double> customHeightTwo;

    private final @NotNull
    RoomType type;

    private final @NotNull
    String houseId;

    private transient volatile int $hashCode;

    private transient volatile boolean $hashCodeMemoized;

    RoomCreateViewModel(double lenght, double height, double width, Input<Double> customLenght,
                        Input<Double> customWidth, Input<Double> customHeightOne, Input<Double> customHeightTwo,
                        @NotNull RoomType type, @NotNull String houseId) {
        this.lenght = lenght;
        this.height = height;
        this.width = width;
        this.customLenght = customLenght;
        this.customWidth = customWidth;
        this.customHeightOne = customHeightOne;
        this.customHeightTwo = customHeightTwo;
        this.type = type;
        this.houseId = houseId;
    }

    /**
     * The Room Lenght
     */
    public double lenght() {
        return this.lenght;
    }

    /**
     * The Room Height
     */
    public double height() {
        return this.height;
    }

    /**
     * The Room Width
     */
    public double width() {
        return this.width;
    }

    /**
     * The Room Custom Lenght (LDat)
     */
    public @Nullable
    Double customLenght() {
        return this.customLenght.value;
    }

    /**
     * The Room Custom Width (ldat)
     */
    public @Nullable
    Double customWidth() {
        return this.customWidth.value;
    }

    /**
     * The Room Custom Height 1 (d1)
     */
    public @Nullable
    Double customHeightOne() {
        return this.customHeightOne.value;
    }

    /**
     * The Room Custom Height 2 (d1)
     */
    public @Nullable
    Double customHeightTwo() {
        return this.customHeightTwo.value;
    }

    public @NotNull
    RoomType type() {
        return this.type;
    }

    /**
     * The House id that contains this room
     */
    public @NotNull
    String houseId() {
        return this.houseId;
    }

    public static Builder builder() {
        return new Builder();
    }

    @Override
    public InputFieldMarshaller marshaller() {
        return writer -> {
            writer.writeDouble("lenght", lenght);
            writer.writeDouble("height", height);
            writer.writeDouble("width", width);
            if (customLenght.defined) {
                writer.writeDouble("customLenght", customLenght.value);
            }
            if (customWidth.defined) {
                writer.writeDouble("customWidth", customWidth.value);
            }
            if (customHeightOne.defined) {
                writer.writeDouble("customHeightOne", customHeightOne.value);
            }
            if (customHeightTwo.defined) {
                writer.writeDouble("customHeightTwo", customHeightTwo.value);
            }
            writer.writeString("type", type.rawValue());
            writer.writeString("houseId", houseId);
        };
    }

    @Override
    public int hashCode() {
        if (!$hashCodeMemoized) {
            int h = 1;
            h *= 1000003;
            h ^= Double.valueOf(lenght).hashCode();
            h *= 1000003;
            h ^= Double.valueOf(height).hashCode();
            h *= 1000003;
            h ^= Double.valueOf(width).hashCode();
            h *= 1000003;
            h ^= customLenght.hashCode();
            h *= 1000003;
            h ^= customWidth.hashCode();
            h *= 1000003;
            h ^= customHeightOne.hashCode();
            h *= 1000003;
            h ^= customHeightTwo.hashCode();
            h *= 1000003;
            h ^= type.hashCode();
            h *= 1000003;
            h ^= houseId.hashCode();
            $hashCode = h;
            $hashCodeMemoized = true;
        }
        return $hashCode;
    }

    @Override
    public boolean equals(Object o) {
        if (o == this) {
            return true;
        }
        if (o instanceof RoomCreateViewModel) {
            RoomCreateViewModel that = (RoomCreateViewModel) o;
            return Double.doubleToLongBits(this.lenght) == Double.doubleToLongBits(that.lenght)
                    && Double.doubleToLongBits(this.height) == Double.doubleToLongBits(that.height)
                    && Double.doubleToLongBits(this.width) == Double.doubleToLongBits(that.width)
                    && this.customLenght.equals(that.customLenght)
                    && this.customWidth.equals(that.customWidth)
                    && this.customHeightOne.equals(that.customHeightOne)
                    && this.customHeightTwo.equals(that.customHeightTwo)
                    && this.type.equals(that.type)
                    && this.houseId.equals(that.houseId);
        }
        return false;
    }

    public static final class Builder {
        private double lenght;

        private double height;

        private double width;

        private Input<Double> customLenght = Input.absent();

        private Input<Double> customWidth = Input.absent();

        private Input<Double> customHeightOne = Input.absent();

        private Input<Double> customHeightTwo = Input.absent();

        private @NotNull
        RoomType type = RoomType.safeValueOf("null");

        private @NotNull
        String houseId = "null";

        Builder() {
        }

        /**
         * The Room Lenght
         */
        public Builder lenght(double lenght) {
            this.lenght = lenght;
            return this;
        }

        /**
         * The Room Height
         */
        public Builder height(double height) {
            this.height = height;
            return this;
        }

        /**
         * The Room Width
         */
        public Builder width(double width) {
            this.width = width;
            return this;
        }

        /**
         * The Room Custom Lenght (LDat)
         */
        public Builder customLenght(@Nullable Double customLenght) {
            this.customLenght = Input.fromNullable(customLenght);
            return this;
        }

        /**
         * The Room Custom Width (ldat)
         */
        public Builder customWidth(@Nullable Double customWidth) {
            this.customWidth = Input.fromNullable(customWidth);
            return this;
        }

        /**
         * The Room Custom Height 1 (d1)
         */
        public Builder customHeightOne(@Nullable Double customHeightOne) {
            this.customHeightOne = Input.fromNullable(customHeightOne);
            return this;
        }

        /**
         * The Room Custom Height 2 (d1)
         */
        public Builder customHeightTwo(@Nullable Double customHeightTwo) {
            this.customHeightTwo = Input.fromNullable(customHeightTwo);
            return this;
        }

        public Builder type(@NotNull RoomType type) {
            this.type = type;
            return this;
        }

        /**
         * The House id that contains this room
         */
        public Builder houseId(@NotNull String houseId) {
            this.houseId = houseId;
            return this;
        }

        /**
         * The Room Custom Lenght (LDat)
         */
        public Builder customLenghtInput(@NotNull Input<Double> customLenght) {
            this.customLenght = Utils.checkNotNull(customLenght, "customLenght == null");
            return this;
        }

        /**
         * The Room Custom Width (ldat)
         */
        public Builder customWidthInput(@NotNull Input<Double> customWidth) {
            this.customWidth = Utils.checkNotNull(customWidth, "customWidth == null");
            return this;
        }

        /**
         * The Room Custom Height 1 (d1)
         */
        public Builder customHeightOneInput(@NotNull Input<Double> customHeightOne) {
            this.customHeightOne = Utils.checkNotNull(customHeightOne, "customHeightOne == null");
            return this;
        }

        /**
         * The Room Custom Height 2 (d1)
         */
        public Builder customHeightTwoInput(@NotNull Input<Double> customHeightTwo) {
            this.customHeightTwo = Utils.checkNotNull(customHeightTwo, "customHeightTwo == null");
            return this;
        }

        public RoomCreateViewModel build() {
            Utils.checkNotNull(type, "type == null");
            Utils.checkNotNull(houseId, "houseId == null");
            return new RoomCreateViewModel(lenght, height, width, customLenght, customWidth, customHeightOne, customHeightTwo, type, houseId);
        }
    }
}
