// AUTO-GENERATED FILE. DO NOT MODIFY.
//
// This class was automatically generated by Apollo GraphQL plugin from the GraphQL queries it found.
// It should not be modified by hand.
//
package com.intDesign.homeHub.infrastructure.graphql.types;

/**
 * Room Object Type
 */
public enum RoomObjectType {
    DOOR("DOOR"),

    WINDOW("WINDOW"),

    INVALID("INVALID"),

    /**
     * Auto generated constant for unknown enum values
     */
    $UNKNOWN("$UNKNOWN");

    private final String rawValue;

    RoomObjectType(String rawValue) {
        this.rawValue = rawValue;
    }

    public String rawValue() {
        return rawValue;
    }

    public static RoomObjectType safeValueOf(String rawValue) {
        for (RoomObjectType enumValue : values()) {
            if (enumValue.rawValue.equals(rawValue)) {
                return enumValue;
            }
        }
        return RoomObjectType.$UNKNOWN;
    }
}
